// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3EzrqdwCLKr1LCsQUFm7tZjPDpW8vhw',
    appId: '1:432872752722:web:d80ba0826cf7f97f59818b',
    messagingSenderId: '432872752722',
    projectId: 'admin-landscaping',
    authDomain: 'admin-landscaping.firebaseapp.com',
    storageBucket: 'admin-landscaping.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfBYCuyTY70ApW-WDEx3uI3TCn6Ppf0k',
    appId: '1:432872752722:android:164e8cc6469811e359818b',
    messagingSenderId: '432872752722',
    projectId: 'admin-landscaping',
    storageBucket: 'admin-landscaping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyWUO75i4aKC7iPjlJRruXqKAJCIhXVnU',
    appId: '1:432872752722:ios:6a2131f56c3c985059818b',
    messagingSenderId: '432872752722',
    projectId: 'admin-landscaping',
    storageBucket: 'admin-landscaping.appspot.com',
    iosClientId: '432872752722-4bfrkbbeq8duk90lcgbnf5ugthkia7f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminLandscapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyWUO75i4aKC7iPjlJRruXqKAJCIhXVnU',
    appId: '1:432872752722:ios:6a2131f56c3c985059818b',
    messagingSenderId: '432872752722',
    projectId: 'admin-landscaping',
    storageBucket: 'admin-landscaping.appspot.com',
    iosClientId: '432872752722-4bfrkbbeq8duk90lcgbnf5ugthkia7f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminLandscapping',
  );
}
